import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cow & Buffalo',
  description: 'Generated by create next app',
  href:"https://i.pinimg.com/564x/77/93/54/7793547f64b9a9560ab993d8ae3bfd58.jpg",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
